export const FETCH_BED_STATUS_REQUEST = "FETCH_BED_STATUS_REQUEST"
export const FETCH_BED_STATUS_SUCCESS = "FETCH_BED_STATUS_SUCCESS"
export const FETCH_BED_STATUS_FAILURE = "FETCH_BED_STATUS_FAILURE"
// export const APPLY_BED_STATUS_FILTER = "APPLY_BED_STATUS_FILTER"

