export const FETCH_IPDPATIENT_REQUEST = "FETCH_IPDPATIENT_REQUEST"
export const FETCH_IPDPATIENT_SUCCESS = "FETCH_IPDPATIENT_SUCCESS"
export const FETCH_IPDPATIENT_FAILURE = "FETCH_IPDPATIENT_FAILURE"
export const FETCH_IPDNO = "FETCH_IPDNO"
// export const APPLY_BED_STATUS_FILTER = "APPLY_BED_STATUS_FILTER"

