export const SET_ITEM_DISCOUNT_ASSISTANT= "SET_ITEM_DISCOUNT_ASSISTANT"
export const SET_ITEM_DISCOUNT_ANESTHESIA = "SET_ITEM_DISCOUNT_ANESTHESIA"
export const SET_ITEM_DISCOUNT_OT = "SET_ITEM_DISCOUNT_OT"

// export const APPLY_BED_STATUS_FILTER = "APPLY_BED_STATUS_FILTER"

